[versions]
agp = "8.12.3"
composeQrCode = "1.0.1"
datastorePreferences = "1.1.7"
kotlin = "2.2.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxSerializationJson = "1.9.0"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.11.0"
composeBom = "2025.09.00"
glance = "1.1.1"
material = "1.13.0"
navigationCompose = "2.9.4"
protobufJava = "4.32.0"
gson = "2.13.1"
cameraX = "1.5.0"
uiUnit = "1.9.1"
material3 = "1.3.2"
reorderable = "3.0.0"
sceneview = "2.3.0"
arcore = "1.50.0"
ossLicenses = "17.3.0"          # seg√∫n doc oficial
ossLicensesPlugin = "0.10.8"
foundation = "1.9.1"
# Ads / Consent
gma = "24.6.0"
ump = "3.2.0"
guava = "33.4.8-android"
runtimeSaveable = "1.9.1"
billing = "8.0.0"
androidx-browser = "1.8.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activityCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
compose-qr-code = { module = "com.lightspark:compose-qr-code", version.ref = "composeQrCode" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3"}
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraX" }
androidx-ui-unit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "uiUnit" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
arsceneview = { module = "io.github.sceneview:arsceneview", version.ref = "sceneview" }
arcore = { module = "com.google.ar:core", version.ref = "arcore" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "ossLicenses" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

# Ads + Consent
google-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "gma" }
google-ump = { module = "com.google.android.ump:user-messaging-platform", version.ref = "ump" }
guava-android = { module = "com.google.guava:guava", version.ref = "guava" }
androidx-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable", version.ref = "runtimeSaveable" }

billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.10" }
oss-licenses = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "ossLicensesPlugin" }

